apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petrus-environments
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      petrus.io/monitored: "true"
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
